version: '3.1'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    restart: always
    ports:
      - 3000:3000
    build: .
    depends_on: 
      - db